#!/usr/bin/env python3
import os
from PIL import Image
import timetablePreparer as prep
import imagesResizer as resizer
import getTimetable
import imageCombiner

PIC_TYPE = "girl"
timetable = Image.open("screenshot.png")
# timetable = getTimetable.get_timetable()

cutted_timetable = prep.cut_timetable_for_the_correct_size(timetable)

# for choice_of_back in range(6,len([name for name in os.listdir('pictures') if os.path.isfile(os.path.join('pictures', name))]) - 1):
for choice_of_back in range(1, 19):
    print(choice_of_back)
    background = 0
    try:
        background = Image.open("pictures/" + PIC_TYPE + "s_for_app/" + PIC_TYPE + "_" + str(choice_of_back) + ".jpg")
    except:
        try:
            background = Image.open(
                "pictures/" + PIC_TYPE + "s_for_app/" + PIC_TYPE + "_" + str(choice_of_back) + ".jpeg")
        except:
            background = Image.open(
                "pictures/" + PIC_TYPE + "s_for_app/" + PIC_TYPE + "_" + str(choice_of_back) + ".png")

    background, resized_timetable = resizer.resize_back_time(background, cutted_timetable)

    # new_timetable = Image.blend(background, prepared_timetable, alpha=0.5)
    clear_timetable = prep.remove_white_back(resized_timetable)
    new_timetable = imageCombiner.add_timetable_with_background(background, clear_timetable)

    new_timetable.save("new_timetables/girls/timetable_" + str(choice_of_back) + ".png")
